version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT:3000
    command: npm run start
